#!/bin/bash

KERNEL_IMAGE=`find /boot/ -name "vmlinuz-*" | sort --version-sort | tail -n1`
if [ ! -f "${KERNEL_IMAGE}" ]; then
  echo "Kernel image not found. Exit."
  exit -1
fi

KERNEL_VER=`echo $KERNEL_IMAGE | sed -r 's%^.*/vmlinuz-(.*)$%\1%'`
if [ -z "${KERNEL_VER}" ]; then
  echo "Kernel version not recognized. Exit."
  exit -1
fi

INITRD="/boot/initrd.img-${KERNEL_VER}"
DT="/usr/lib/linux-image-${KERNEL_VER}/marvell/armada-3720-turris-mox.dtb"

echo "Kernel Image: $KERNEL_IMAGE"
echo "DT: $DT"
echo "InitRD: $INITRD"

cat >/boot/boot.txt <<EOF
setenv bootargs 'console=ttyMV0,115200 earlycon=ar3700_uart,0xd0012000 root=/dev/mmcblk0p1 rootwait'
setenv mox_boot_lk 'load mmc 0 \${kernel_addr_r} ${KERNEL_IMAGE}'
setenv mox_boot_ldt 'load mmc 0 \${fdt_addr_r} ${DT}'
EOF

if [ -f "${INITRD}" ]; then
cat >>/boot/boot.txt <<EOF
setenv mox_boot_lrd 'load mmc 0 \${ramdisk_addr_r} ${INITRD};'
setenv mox_boot_brd 'booti \${kernel_addr_r} \${ramdisk_addr_r}:0x\${filesize} \${fdt_addr_r};'
setenv mox_boot 'run mox_boot_lk; run mox_boot_ldt; run mox_boot_lrd; run mox_boot_brd'
run mox_boot
EOF
else
cat >>/boot/boot.txt <<EOF
setenv mox_boot_brd 'booti \${kernel_addr_r} - \${fdt_addr_r};'
setenv mox_boot 'run mox_boot_lk; run mox_boot_ldt; run mox_boot_brd'
run mox_boot
EOF
fi

rm -f /boot/boot.scr
mkimage -T script -C none -n boot -d /boot/boot.txt /boot/boot.scr

