#!/bin/bash

KERNEL_IMAGE=`find /boot/ -name "vmlinuz-*" | sort --version-sort | tail -n1`
if [ ! -f "${KERNEL_IMAGE}" ]; then
  echo "Kernel image not found. Exit."
  exit -1
fi

KERNEL_VER=`echo $KERNEL_IMAGE | sed -r 's%^.*/vmlinuz-(.*)$%\1%'`
if [ -z "${KERNEL_VER}" ]; then
  echo "Kernel version not recognized. Exit."
  exit -1
fi

INITRD="/boot/initrd.img-${KERNEL_VER}"
DT="/usr/lib/linux-image-${KERNEL_VER}/marvell/armada-3720-turris-mox.dtb"

echo "Kernel Image: $KERNEL_IMAGE"
echo "DT: $DT"
echo "InitRD: $INITRD"

if [ -f "${INITRD}" ]; then
  INITRD_SIZE=`printf "0x%x\n" $(stat -c "%s" ${INITRD})`
cat >/boot/boot.txt <<EOF
setenv bootargs 'console=ttyMV0,115200 earlycon=ar3700_uart,0xd0012000 root=/dev/mmcblk1p1 rootwait'
setenv mox_boot 'load mmc 0 \${kernel_addr_r} ${KERNEL_IMAGE}; load mmc 0 \${fdt_addr_r} ${DT}; load mmc 0 \${ramdisk_addr_r} ${INITRD}; booti \${kernel_addr_r} \${ramdisk_addr_r}:${INITRD_SIZE} \${fdt_addr_r};'
run mox_boot
EOF
else
cat >/boot/boot.txt <<EOF
setenv bootargs 'console=ttyMV0,115200 earlycon=ar3700_uart,0xd0012000 root=/dev/mmcblk1p1 rootwait'
setenv mox_boot 'load mmc 0 \${kernel_addr_r} ${KERNEL_IMAGE}; load mmc 0 \${fdt_addr_r} ${DT}; booti \${kernel_addr_r} - \${fdt_addr_r};'
run mox_boot
EOF
#setenv mox_boot 'run selectwan; load mmc 0 \${kernel_addr_r} /@${KERNEL_IMAGE}; load mmc 0 \${fdt_addr_r} /@/boot/dtb-wan\$wan; bootz \${kernel_addr_r} - \${fdt_addr_r};'
fi

rm -f /boot/boot.scr
mkimage -T script -C none -n boot -d /boot/boot.txt /boot/boot.scr

