#!/bin/bash

KERNEL_IMAGE=`find /boot/ -name "vmlinuz-*" | sort --version-sort | tail -n1`
if [ ! -f "${KERNEL_IMAGE}" ]; then
  echo "Kernel image not found. Exit."
  exit -1
fi

KERNEL_VER=`echo $KERNEL_IMAGE | sed -r 's%^.*/vmlinuz-(.*)$%\1%'`
if [ -z "${KERNEL_VER}" ]; then
  echo "Kernel version not recognized. Exit."
  exit -1
fi

INITRD="/boot/initrd.img-${KERNEL_VER}"
DTPHY="/usr/lib/linux-image-${KERNEL_VER}/armada-385-turris-omnia-phy.dtb"
DTSFP="/usr/lib/linux-image-${KERNEL_VER}/armada-385-turris-omnia-sfp.dtb"

if [ -f "${DTPHY}" ]; then
  rm -f /boot/dtb-wanphy
  ln -s $DTPHY /boot/dtb-wanphy
else
  #DTCOMMON="/usr/lib/linux-image-${KERNEL_VER}/armada-385-turris-omnia.dtb"
  rm -f /boot/dtb-wanphy
  ln -s /boot/armada-385-turris-omnia-phy.dtb /boot/dtb-wanphy
fi

if [ -f "${DTSFP}" ]; then
  rm -f /boot/dtb-wansfp
  ln -s $DTSFP /boot/dtb-wansfp
else
  #DTCOMMON="/usr/lib/linux-image-${KERNEL_VER}/armada-385-turris-omnia.dtb"
  rm -f /boot/dtb-wansfp
  ln -s /boot/armada-385-turris-omnia-sfp.dtb /boot/dtb-wansfp

fi

echo "Kernel Image: $KERNEL_IMAGE"
echo "InitRD: $INITRD"

if [ -f "${INITRD}" ]; then
  INITRD_SIZE=`printf "0x%x\n" $(stat -c "%s" ${INITRD})`
cat >/boot/boot.txt <<EOF
setenv bootargs "earlyprintk console=\$console pcie_aspm=off root=b301 rootdelay=2 rootflags=subvol=@,commit=5 rw"
setenv selectwan 'if gpio input gpio@71_4; then echo SFP; setenv wan sfp; else echo PHY; setenv wan phy; fi'
setenv omnia_boot 'run selectwan; load mmc 0 \${kernel_addr_r} /@${KERNEL_IMAGE}; load mmc 0 \${fdt_addr_r} /@/boot/dtb-wan\$wan; load mmc 0 \${ramdisk_addr_r} /@${INITRD}; bootz \${kernel_addr_r} \${ramdisk_addr_r}:${INITRD_SIZE} \${fdt_addr_r};'
run omnia_boot
EOF
else
cat >/boot/boot.txt <<EOF
setenv bootargs "earlyprintk console=\$console pcie_aspm=off root=b301 rootdelay=2 rootflags=subvol=@,commit=5 rw"
setenv selectwan 'if gpio input gpio@71_4; then echo SFP; setenv wan sfp; else echo PHY; setenv wan phy; fi'
setenv omnia_boot 'run selectwan; load mmc 0 \${kernel_addr_r} /@${KERNEL_IMAGE}; load mmc 0 \${fdt_addr_r} /@/boot/dtb-wan\$wan; bootz \${kernel_addr_r} - \${fdt_addr_r};'
run omnia_boot
EOF
fi

rm -f /boot/boot.scr
mkimage -T script -C none -n boot -d /boot/boot.txt /boot/boot.scr

